### ISSUE TITLE
xunit 2 support?

### ISSUE THREAD

**Issue by cherrydev** [daniel-chambers/xunit.ioc#6]
It would be fantastic to have support for xunit 2, if possible.

**Comment by daniel-chambers** [comment]
Now that xunit 2.0 is RTM-ed I'll definitely look into it. :) I was waiting until the development had stabilized before making any changes here.

**Comment by cherrydev** [comment]
I've taken a bit of a look at the issue and right off the bat there's no `RunWithAttribute` and there don't appear to be any direct replacements.
To be honest, I'm disappointed that xunit 2 wasn't designed with DI in mind, even though fixtures are designed precisely to fill constructor arguments on the test classes, but only in an extremely inflexible way.

**Comment by sethreidnz** [comment]
Any progress on this?

**Comment by daniel-chambers** [comment]
xunit 2 is very different to xunit 1. I'm not entirely sure it's possible to implement this project in it; the old extensibility points don't exist anymore (see @cherrydev's comment above), though I'm happy to see some spike code or ideas to prove me wrong.

**Comment by sethreidnz** [comment]
You are probably correct. Its ubfortunste as integration testing without DI is quite painful.

**Comment by mdissel** [comment]
any updates on this issue?

**Comment by daniel-chambers** [comment]
No; as I mentioned previously, due to the large differences unless someone discovers a way to implement the spirit of this project in xunit 2, we'll only support xunit 1.

**Comment by dennisroche** [comment]
@daniel-chambers I've found an extension point by implementing an `XunitTestFramework`. It is a bit of a yak-shave as you need to several classes to dig down to the actual `override` where you can resolve constructor dependencies (e.g. fixtures) with things from your container.

**Comment by daniel-chambers** [comment]
@dennisroche Would love to see a PR, if you're interested in shaving that yak :)

**Comment by Rookian** [comment]
Hi guys,

take a look at my repository: https://github.com/Rookian/xUnitDependencyInjection

Feel free to give some feedback.

**Comment by dennisroche** [comment]
@daniel-chambers i'm already one with the yak. https://github.com/dennisroche/xunit.ioc.autofac

@Rookian and myself have taken a very similar approach by extending the `XunitTestFramework`.

**Comment by daniel-chambers** [comment]
@dennisroche Nice one. 👍

**Comment by dennisroche** [comment]
Thanks. 

Unfortunately, as it is such a different approach for xUnit2 it would be difficult to make it a PR for this project.

**Comment by daniel-chambers** [comment]
That's fine; I'm happy to let this project just support xunit 1 and people wanting xunit 2 can use your project instead.

Given this stance, I'm going to close this issue.

**Comment by VictorioBerra** [comment]
## This is getting annoying.

For anyone reading this, @dennisroche fork [does not support the Theory Attribute. He has abandoned his fork and hasn't been accepting PRs.](https://github.com/dennisroche/xunit.ioc.autofac/pull/12#issuecomment-342415572)

[@dabide](https://github.com/dabide) ended up forking the project and adding support for it here: https://github.com/MinistryOfMagic/xunit.frameworks.autofac

This has me questioning if using these are even a good idea at all.

**Comment by dennisroche** [comment]
@VictorioBerra thanks for mentioning me as I didn't see the other notifications/pr which is why they weren't merged 😢. 

I agree with you. I have found that dependency injection isn't required in tests and the cost of maintaining a custom test runner for `xunit` introduces too many issues/breakages.

**Comment by VictorioBerra** [comment]
No problem. Yes I agree.

**Comment by daniel-chambers** [comment]
Yes, as far as I'm concerned this project and its approach is deprecated. I'm more than happy for the torch to be carried by @dabide at https://github.com/MinistryOfMagic/xunit.frameworks.autofac.
