### ISSUE TITLE
Updating 'xunit 1.9.0.1566' to 'xunit 2.1.0' failed. Unable to find versions of 'xunit.ioc, xunit.ioc.autofac' that are compatible with 'xunit 2.1.0'.

### ISSUE THREAD

**Issue by RavindraBarapatre** [daniel-chambers/xunit.ioc#8]
![image](https://cloud.githubusercontent.com/assets/11921979/19064220/80c240ae-8a29-11e6-9e7a-44254fdfad74.png)

Please change xunit (>= 1.9.0 && < 2.0.0) condition. we are not able to upgrade packages.

**Comment by daniel-chambers** [comment]
I've decided not to support xUnit 2 for this project because xUnit 2 is too different (see #6). Other projects exist which you might try as an alternative if you need xUnit 2, for example https://github.com/dennisroche/xunit.ioc.autofac.
